language: python

sudo: required
dist: trusty

python:
  - 2.7
  - 3.5

install:
  - pip install -U cython numpy nose
  - python -c 'import numpy; print(numpy.get_include())'
  - python setup.py install

script:
 - python setup.py test
